### ISSUE TITLE
simple-OSC/simple-OSC.h: No such file or directory

### ISSUE THREAD

**Issue by Druuka** [ameisso/simple-OSC#1]

**Comment by ameisso** [comment]
Hello Druuka, 
Did you manage to fix it? 
What was it?

Best 
Antoine M*

**Comment by Druuka** [comment]
Antoine,

Sorry for posting that in the first place.  I was attempting to verify with a core chosen instead of a photon.  Once I selected the correct product it verified properly.  

Thanks,

Andrew

**Comment by ameisso** [comment]
Hello @Druuka 

No problem, seems that it's not working on the core at the moment.
Looks like a casting problem (string to char*) This might evolve in the future. If yes i'll let you know.

Regards

**Comment by Druuka** [comment]
Thanks,

I appreciate the work you have done to implement OSC in this environment.  

Andrew Webberley
